### ISSUE TITLE
Coordinator 개선 방안

### ISSUE THREAD

**Issue by JungJiSeung** [boostcampwm-2021/iOS07-DoolDa#104]
## 내용
* 기존 parent와 children을 포함하고 있어 순환참조를 유발하는 Coordinator 개선
    1. 사건의 발단.
        * Coordinator Pattern 스터디중 Coordinator를 children에 저장하지 않아서 메모리에서 사라졌었다.
               <- 내 생각엔 처음 생성한 AppCoordinator를 SceneDelegate에서 저장하지 않아서 사라진건데, 착각했던것 같다.
        * 생성한 coordinator를 children에 저장해 메모리 참조 카운트를 잃지 않으려고 했다.
        * ViewController에서 dismiss시 parent에 저장된 자기 자신의 Coordinator를 제거하기 위해 Parent를 참조 할 수 있도록 했다.
        * Coordinator에 작성된 removeFromParent를 호출하지 않고 dismiss시킬 때 메모리에서 제거되지 않는 현상 발생
    2. 해결 방안.
        * 현재 작성된 코드에서 parent와, children을 제거한다.
              <- 제거해도 ViewModel이 Coordinator를 참조하고 있어 ViewModel을 참조하는 ViewController가 메모리에서 사라지지 않는이상 사라지지 않음

---

위 해결방안을 적용한 Coordinator

[변경된 코드를 적용한 브랜치](https://github.com/boostcampwm-2021/iOS07-DoolDa/tree/refactor/improve_coordinator) <- 1차 데모 코드에 적용했습니다.

```swift
class Coordinator {
//    private var parent: Coordinator?
//    private var children: [Coordinator] = []
    let presenter: UINavigationController
    
    init(presenter: UINavigationController) { //}, parent: Coordinator? = nil) {
        self.presenter = presenter
//        self.parent = parent
    }
//
//    func add(child: Coordinator) {
//        self.children.append(child)
//    }
//
//    func removeFromParent() {
//        guard let parent = parent else { return }
//        parent.children = parent.children.filter { $0 != self }
//    }
//
    func start() {
        fatalError("start method should be implemented")
    }
}
```

**Comment by Yabby1997** [comment]
좋네요 갑시다!
