### ISSUE TITLE
다이어리 편집화면 사진 편집기능에서 page indicator가 정상적인 인덱스를 표시하지 않는 문제

### ISSUE THREAD

**Issue by Yabby1997** [boostcampwm-2021/iOS07-DoolDa#597]
### 요약
다이어리 편집화면 사진 편집기능에서 page indicator가 정상적인 인덱스를 표시하지 않는 문제

### 재현 방법
다이어리 편집 > 사진선택 > 손을 떼지 않고 스크롤해 임의의 사진 템플릿을 선택

### 예상 결과 
현재 보여지는 템플릿에 맞춰 page indicator가 알맞게 표시됨

### 실제 결과

현재 보여지는 템플릿과 page indicator가 일치하지 않음. (영상은 문제있어서 제거했습니다. 실제 편집은 현재 보여지는 템플릿으로 진행됨)

**Comment by ralph-101-dev** [comment]
@Yabby1997 승훈님 요거 재현영상 부탁드려도 될까요?? 🥺
글로만 보니까 재현하기가 어려워요 ㅜㅜ

**Comment by Yabby1997** [comment]
@ralph-101-dev  너무 늦게 봤ㄷ...ㅏ
