### ISSUE TITLE
2주차 통합 테스트 버그리포트

### ISSUE THREAD

**Issue by JungJiSeung** [boostcampwm-2021/iOS07-DoolDa#83]
### 요약
* 이미 연결 완료된 UserId로 친구 연결시 친구가 맺어지는 현상 발생
* 서버에 존재하지 않는 Id입력시 친구 연결이 완료되는 현상 발생 <- 캐시 관련 문제 같다.
* Firebase 캐시 문제로 네트워크 연결되지 않은 상태에서 데이터를 가져와 다이어리 화면으로 전환되는 현상 발생
* 작성된 테스트 일부는 실패, 일부 테스트 타겟의 파일들은 스키마에서 지워진듯 싶습니다.

**Comment by minglely** [comment]
*  이미 연결 완료된 UserId로 친구 연결시 친구가 맺어지는 현상 발생
   *  현재 pairing할 때 친구 id의 pairid가 공백임을 확인해야하는데 이걸 확인하는 과정이 없어서 벌어지는 문제
   * 이 부분을 repository에 넣을 지 usecase에 넣을 지는 상의해봐야함
